# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='release_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
