# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171106_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='build_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
