# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_app_build_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=20)),
                ('build_name', models.CharField(max_length=20, unique=True)),
                ('version', models.IntegerField()),
                ('size', models.BigIntegerField()),
                ('release_note', models.TextField(max_length=200)),
                ('release_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
